/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package atoms;

import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author chamod
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setIcon();
    }
    
    DBOperations dbOps=new DBOperations();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblGo = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblForgotPassword = new javax.swing.JLabel();
        lblSignIn = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 730));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login System nomal mod.png"))); // NOI18N
        lblGo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblGoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblGoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblGoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblGoMouseReleased(evt);
            }
        });
        getContentPane().add(lblGo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 100, 130, 520));

        txtUsername.setBackground(new java.awt.Color(240, 240, 240));
        txtUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(51, 51, 51));
        txtUsername.setBorder(null);
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(935, 350, 240, 35));

        lblForgotPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fogot username mouse normal.png"))); // NOI18N
        lblForgotPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblForgotPasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblForgotPasswordMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblForgotPasswordMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblForgotPasswordMouseReleased(evt);
            }
        });
        getContentPane().add(lblForgotPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 480, 210, 30));

        lblSignIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Sign in normal mod.png"))); // NOI18N
        lblSignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSignInMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSignInMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSignInMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblSignInMouseReleased(evt);
            }
        });
        getContentPane().add(lblSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1012, 551, 210, 50));

        txtPassword.setBackground(new java.awt.Color(240, 240, 240));
        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(51, 51, 51));
        txtPassword.setBorder(null);
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(935, 435, 240, 35));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LOGIN WINDOW.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblGoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGoMouseEntered
       ImageIcon II=new ImageIcon(getClass().getResource("/Images/Login System mouse enter.png"));
       lblGo.setIcon(II);
    }//GEN-LAST:event_lblGoMouseEntered

    private void lblGoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGoMousePressed
        ImageIcon II=new ImageIcon(getClass().getResource("/Images/Login System mouse clicked.png"));
        lblGo.setIcon(II);
    }//GEN-LAST:event_lblGoMousePressed

    private void lblGoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGoMouseExited
        ImageIcon II=new ImageIcon(getClass().getResource("/Images/Login System nomal mod.png"));
        lblGo.setIcon(II);
    }//GEN-LAST:event_lblGoMouseExited

    private void lblForgotPasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblForgotPasswordMouseEntered
        ImageIcon II=new ImageIcon(getClass().getResource("/Images/Fogot username mouse enterd.png"));
       lblForgotPassword.setIcon(II);
    }//GEN-LAST:event_lblForgotPasswordMouseEntered

    private void lblForgotPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblForgotPasswordMousePressed
        ImageIcon II=new ImageIcon(getClass().getResource("/Images/Fogot username mouse Clicked.png"));
       lblForgotPassword.setIcon(II);
    }//GEN-LAST:event_lblForgotPasswordMousePressed

    private void lblForgotPasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblForgotPasswordMouseExited
        ImageIcon II=new ImageIcon(getClass().getResource("/Images/Fogot username mouse normal.png"));
       lblForgotPassword.setIcon(II);
    }//GEN-LAST:event_lblForgotPasswordMouseExited

    private void lblSignInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignInMouseEntered
        ImageIcon II=new ImageIcon(getClass().getResource("/Images/Sign in mouse enter.png"));
        lblSignIn.setIcon(II);
    }//GEN-LAST:event_lblSignInMouseEntered

    private void lblSignInMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignInMousePressed
        ImageIcon II=new ImageIcon(getClass().getResource("/Images/Sign in mouse clicked.png"));
        lblSignIn.setIcon(II);
    }//GEN-LAST:event_lblSignInMousePressed

    private void lblSignInMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignInMouseExited
       ImageIcon II=new ImageIcon(getClass().getResource("/Images/Sign in normal mod.png"));
       lblSignIn.setIcon(II);
    }//GEN-LAST:event_lblSignInMouseExited

    private void lblGoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGoMouseReleased
        if(txtUsername.getText().equals("admin")){
            AdminView av=new AdminView();
            av.setVisible(true);
        } else {
            int result = dbOps.checkUsernamePassword(txtUsername.getText(), MD5.md5(txtPassword.getText()));
            if (result == 1) {
                Atoms.username = txtUsername.getText();
                MainFrame mainFrame = new MainFrame();
                mainFrame.setVisible(true);
                MiddleFrame mf = new MiddleFrame();
                mf.setVisible(true);
                this.dispose();
            } else if (result == 0) {
                JOptionPane.showMessageDialog(this, "Username Password miss match!");
            } else {
                JOptionPane.showMessageDialog(this, "error occur while searching!");
            }
        }
    }//GEN-LAST:event_lblGoMouseReleased

    private void lblForgotPasswordMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblForgotPasswordMouseReleased
        
    }//GEN-LAST:event_lblForgotPasswordMouseReleased

    private void lblSignInMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignInMouseReleased
        NewUser newUser=new NewUser();
        newUser.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblSignInMouseReleased

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblForgotPassword;
    private javax.swing.JLabel lblGo;
    private javax.swing.JLabel lblSignIn;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));}
}
