/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package atoms;

import javax.swing.ImageIcon;
import java.awt.Toolkit;
/**
 *
 * @author chamod
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setIcon();
        lblUsername.setText(Atoms.username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDashboard = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblGroup = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        lblTasks = new javax.swing.JLabel();
        lblEvents = new javax.swing.JLabel();
        lblAnalys = new javax.swing.JLabel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Main Frame");
        setPreferredSize(new java.awt.Dimension(1366, 730));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/DASH NOT.png"))); // NOI18N
        lblDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDashboardMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblDashboardMousePressed(evt);
            }
        });
        getContentPane().add(lblDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 300, 70));

        lblUsername.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(51, 153, 255));
        lblUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblUsernameMousePressed(evt);
            }
        });
        getContentPane().add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 140, 30));

        lblGroup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/GROUP NOT.png"))); // NOI18N
        lblGroup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblGroupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblGroupMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblGroupMousePressed(evt);
            }
        });
        getContentPane().add(lblGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 290, 70));

        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblLogoutMousePressed(evt);
            }
        });
        getContentPane().add(lblLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 40, 40));

        lblTasks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TASKS NOT.png"))); // NOI18N
        lblTasks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTasksMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblTasksMouseExited(evt);
            }
        });
        getContentPane().add(lblTasks, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 290, 70));

        lblEvents.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/EVENTS NOT.png"))); // NOI18N
        lblEvents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEventsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEventsMouseExited(evt);
            }
        });
        getContentPane().add(lblEvents, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 290, 70));

        lblAnalys.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ANALY.png"))); // NOI18N
        lblAnalys.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAnalysMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAnalysMouseExited(evt);
            }
        });
        getContentPane().add(lblAnalys, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 290, 60));
        getContentPane().add(jCalendar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 50, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dash PLAIN3.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, 1330, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDashboardMouseEntered
        ImageIcon II=new ImageIcon(getClass().getResource("/Images/DASH SELECT.png"));
        lblDashboard.setIcon(II);
    }//GEN-LAST:event_lblDashboardMouseEntered

    private void lblDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDashboardMouseExited
        ImageIcon II=new ImageIcon(getClass().getResource("/Images/DASH NOT.png"));
        lblDashboard.setIcon(II);
    }//GEN-LAST:event_lblDashboardMouseExited

    private void lblDashboardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDashboardMousePressed
        Dashboard dashBoard=new Dashboard();
        dashBoard.setVisible(true);
    }//GEN-LAST:event_lblDashboardMousePressed

    private void lblGroupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGroupMouseEntered
        ImageIcon II=new ImageIcon(getClass().getResource("/Images/GROUP SEL.png"));
        lblGroup.setIcon(II);
    }//GEN-LAST:event_lblGroupMouseEntered

    private void lblGroupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGroupMouseExited
        ImageIcon II=new ImageIcon(getClass().getResource("/Images/GROUP NOT.png"));
        lblGroup.setIcon(II);
    }//GEN-LAST:event_lblGroupMouseExited

    private void lblGroupMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGroupMousePressed
        GroupFrame groupFrame=new GroupFrame();
        groupFrame.setVisible(true);
    }//GEN-LAST:event_lblGroupMousePressed

    private void lblUsernameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsernameMousePressed
        Profile profile=new Profile();
        profile.setVisible(true);
    }//GEN-LAST:event_lblUsernameMousePressed

    private void lblLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseEntered
       
    }//GEN-LAST:event_lblLogoutMouseEntered

    private void lblLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblLogoutMouseExited

    private void lblLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMousePressed
        LogOut lo=new LogOut();
        lo.setVisible(true);
    }//GEN-LAST:event_lblLogoutMousePressed

    private void lblTasksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTasksMouseEntered
        ImageIcon II=new ImageIcon(getClass().getResource("/Images/TAS SEL.png"));
        lblTasks.setIcon(II);
    }//GEN-LAST:event_lblTasksMouseEntered

    private void lblTasksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTasksMouseExited
        ImageIcon II=new ImageIcon(getClass().getResource("/Images/TASKS NOT.png"));
        lblTasks.setIcon(II);
    }//GEN-LAST:event_lblTasksMouseExited

    private void lblEventsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEventsMouseEntered
        ImageIcon II=new ImageIcon(getClass().getResource("/Images/EVEN SEL.png"));
        lblEvents.setIcon(II);
    }//GEN-LAST:event_lblEventsMouseEntered

    private void lblEventsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEventsMouseExited
        ImageIcon II=new ImageIcon(getClass().getResource("/Images/EVENTS NOT.png"));
        lblEvents.setIcon(II);
    }//GEN-LAST:event_lblEventsMouseExited

    private void lblAnalysMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnalysMouseEntered
        ImageIcon II=new ImageIcon(getClass().getResource("/Images/ANA SELECT.png"));
        lblAnalys.setIcon(II);
    }//GEN-LAST:event_lblAnalysMouseEntered

    private void lblAnalysMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnalysMouseExited
        ImageIcon II=new ImageIcon(getClass().getResource("/Images/ANALY.png"));
        lblAnalys.setIcon(II);
    }//GEN-LAST:event_lblAnalysMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAnalys;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblEvents;
    private javax.swing.JLabel lblGroup;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblTasks;
    private javax.swing.JLabel lblUsername;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
    }
}
