/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package atoms;

import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author chamod
 */
public class NewUser extends javax.swing.JFrame {

    /**
     * Creates new form NewUser
     */
    DBOperations dbOps=new DBOperations();
    public NewUser() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txtUsername = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtConfirmPassword = new javax.swing.JPasswordField();
        lblCancel = new javax.swing.JLabel();
        lblGo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New User");
        setPreferredSize(new java.awt.Dimension(1366, 730));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsername.setBackground(new java.awt.Color(240, 240, 240));
        txtUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtUsername.setBorder(null);
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 250, 240, 35));

        txtEmail.setBackground(new java.awt.Color(240, 240, 240));
        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEmail.setBorder(null);
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 340, 240, 35));

        txtPassword.setBackground(new java.awt.Color(240, 240, 240));
        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPassword.setBorder(null);
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 430, 240, 35));

        txtConfirmPassword.setBackground(new java.awt.Color(240, 240, 240));
        txtConfirmPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtConfirmPassword.setBorder(null);
        getContentPane().add(txtConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 520, 240, 35));

        lblCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancelNormal.png"))); // NOI18N
        lblCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCancelMouseExited(evt);
            }
        });
        getContentPane().add(lblCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 586, 170, 60));

        lblGo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/GoNormal .png"))); // NOI18N
        lblGo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblGoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblGoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblGoMousePressed(evt);
            }
        });
        getContentPane().add(lblGo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1143, 50, 150, 630));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Sign Up.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelMouseEntered
        ImageIcon II=new ImageIcon(getClass().getResource("/Images/cancel clicked.png"));
        lblCancel.setIcon(II);
    }//GEN-LAST:event_lblCancelMouseEntered

    private void lblCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelMouseExited
        ImageIcon II=new ImageIcon(getClass().getResource("/Images/cancelNormal.png"));
        lblCancel.setIcon(II);
    }//GEN-LAST:event_lblCancelMouseExited

    private void lblGoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGoMouseEntered
        ImageIcon II=new ImageIcon(getClass().getResource("/Images/goClicked.png"));
        lblGo.setIcon(II);
    }//GEN-LAST:event_lblGoMouseEntered

    private void lblGoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGoMouseExited
        ImageIcon II=new ImageIcon(getClass().getResource("/Images/GoNormal .png"));
        lblGo.setIcon(II);
    }//GEN-LAST:event_lblGoMouseExited

    private void lblCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelMouseClicked
        this.dispose();
        Login login=new Login();
        login.setVisible(true);
    }//GEN-LAST:event_lblCancelMouseClicked

    private void lblGoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGoMousePressed
        if(txtPassword.getText().equals(txtConfirmPassword.getText())){
            int result=dbOps.isThereUsername(null);
            if(result==0){
                User user=new User();
                user.setUsername(txtUsername.getText());
                user.setPassword(MD5.md5(txtPassword.getText()));
                user.setEmail(txtEmail.getText());
                dbOps.addUser(user);
                JOptionPane.showMessageDialog(this,"New account created");
                Atoms.username=txtUsername.getText();
                MainFrame mainframe=new MainFrame();
                mainframe.setVisible(true);
                this.dispose();
            }else if(result==1){
                JOptionPane.showMessageDialog(this,"Username already exist!");
            }else{
                JOptionPane.showMessageDialog(this,"Error occur while searching username!");
            }
        }else{
            JOptionPane.showMessageDialog(this,"Password miss match!");
        }
    }//GEN-LAST:event_lblGoMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblCancel;
    private javax.swing.JLabel lblGo;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png"))); }
}
